config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :games, only: [:index, :show, :destroy]
    resources :stats, only: [:index]
  end

  resources :games, only: [:index, :new, :create, :show, :destroy] do
    resources :players, only: [:new, :create, :destroy]
  end

  resources :sports, only: [:new, :create]

  resources :users, only: [:show]

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  belongs_to :sport
  has_many :players, dependent: :destroy

  validates :user, presence: true
  validates :description, length: { maximum: 50 }
  validates :sport, presence: true
  validates :street_address, presence: true
  validates :start_date, presence: true
  validates :max_players, presence: true,
    numericality: { only_integer: true }

  include PgSearch
  pg_search_scope :search,
    :against => :street_address,
    :using => {
      :tsearch => { :prefix => true }
    }

  def full?
    if players.count == max_players
      "Full"
    else
      "#{players.count} / #{max_players}"
    end
  end

  def description?
    if description.empty?
      "N/A"
    else
      description
    end
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :game

  validates :user, presence: true, uniqueness: { scope: :game }
  validates :game, presence: true
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :games

  validates :name, presence: true, uniqueness: true
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  def self.sports
    games = Game.all
    sports = []
    games.each do |game|
      sports << game.sport
    end

    sports.to_a.map!(&:serializable_hash)
    array = []
    sports.each do |sport|
      array << sport["name"]
    end

    @@sport_count = Hash.new(0)
    array.each{|key| @@sport_count[key] += 1}
    @@sport_count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games
  has_many :players

  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_filter :authorize_admin!

  def index
    @games = Game.all
  end
end

app/controllers/admin/stats_controller.rb
class Admin::StatsController < ApplicationController
  before_filter :authorize_admin!

  def index
    @games = Game.all
  end

  protected

  def stat_params
    params.require(:game).permit(:user_id, :description, :sport_id, :start_date, :street_address, :max_players)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authorize_admin!

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id]).destroy
    flash[:notice] = 'User Deleted'
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(
        :name,
        :email,
        :password,
        :password_confirmation
      )
    end
    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit(
        :name,
        :email,
        :password,
        :password_confirmation
      )
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(
        :name,
        :email,
        :password,
        :password_confirmation,
        :current_password
      )
    end
  end

  def authorize_admin!
    if current_user.nil? || !current_user.admin?
      flash[:notice] = "You are not authorized to view this resource."
      redirect_to root_path
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    if params[:q].present?
      @games = Game.search(params[:q]).order("start_date DESC")
    else
      @games = Game.all.order("start_date DESC")
    end
  end

  def show
    @game = Game.find(params[:id])
    @address = @game.street_address
    @players = Player.where(game: @game)
    @player = Player.find_by(user: current_user, game: @game)
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user = current_user
    @player = Player.find_or_initialize_by(game: @game, user: current_user)

    if @game.save && @player.save
      flash[:success] = "Game Created"
      redirect_to game_path(@game)
    else
      flash.now[:alert] = @game.errors.full_messages.join("\n")
      render :new
    end
  end

  def destroy
    @game = Game.find(params[:id]).destroy
    flash[:success] = "Game Deleted"
    redirect_to games_path
  end

  protected

  def game_params
    params.require(:game).permit(:user_id, :description, :sport_id, :start_date, :street_address, :max_players)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def new
    @game = Game.new
  end

  def create
    @game = Game.find(params[:game_id])
    @player = Player.find_or_initialize_by(game: @game, user: current_user) #replace @game with ajax data ('params')
    @player.save
    flash[:success] = "Game Joined"
    redirect_to game_path(@game)
  end

  def destroy
    @game = Game.find(params[:game_id])
    @player = Player.find_by(user: current_user, game: @game).destroy
    flash[:success] = "You've left this game"
    redirect_to game_path(@game)
  end

  protected

  def player_params
    params.require(:player).permit(:user_id, :game_id)
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :authenticate_user!

  def new
    @sport = Sport.new
    @sports = Sport.all.order(:name)
  end

  def create
    @sport = Sport.new(sport_params)
    @sports = Sport.all.order(:name)

    if @sport.save
      flash[:success] = "Sport Added"
      redirect_to new_game_path
    else
      flash.now[:alert] = @sport.errors.full_messages.join(":( ")
      render :new
    end
  end

  protected

  def sport_params
    params.require(:sport).permit(:name)
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

  def index
    @games = Game.all
  end

  protected

  def stat_params
    params.require(:game).permit(:user_id, :description, :sport_id, :start_date, :street_address, :max_players)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @games = Player.where(user: current_user)
  end

end

app/views/admin/games/index.html.erb
<div id="featured">

<div class="row">
  <div class="small-10 columns small-centered">
    <div class="create-row large-8 small-12 small-centered columns">

      <% if params[:q].present? %>
        <h2 id="index-header">Games matching</h2><p>"<%= params[:q] %>"</p>
      <% else %>
        <h2 id="index-header">Games</h2>
      <% end %>

      <%= link_to new_game_path, class:"create tiny button expand", id:"new game" do %>
        <i class="fa fa-plus"></i> New Game
      <% end %>
    </div>

    <table id="table_id" class="display">
      <thead>
        <tr>
          <th>Sport</th>
          <th>Address</th>
          <th>Date</th>
          <th>Time</th>
          <th>Additional info</th>
          <th>Players</th>
        </tr>
      </thead>

      <tbody>
        <% @games.each do |game| %>
        <tr>
          <td><%= game.sport.name %></td>
          <td><%= link_to game.street_address, game_path(game) %></td>
          <td><%= game.start_date %></td>
          <td><%= game.start_date.strftime("%l:%M%p") %></td>
            <% if game.description.empty? %>
              <td>N/A</td>
            <% else %>
              <td><%= game.description %></td>
            <% end %>
          </td>
            <% if game.players.count == game.max_players %>
          <td>FULL</td>
            <% else %>
          <td><%= game.players.count %>/<%= game.max_players %></td>
            <% end %>
          <td><%= button_to 'Delete Game', game_path(game), method: :delete %>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

</div>

app/views/admin/stats/index.html.erb
<div id="featured">

  <div class="row">
    <div class="small-10 columns small-centered">
      <div class="create-row large-8 small-12 small-centered columns">

          <h2 id="index-header">Data and Statistics</h2>

      </div>

      <%= pie_chart Stat.sports %>

        <table id="table_id" class="display">
          <thead>
            <tr>
              <th>Sport</th>
              <th>Address</th>
              <th>Date</th>
              <th>Time</th>
              <th>Additional info</th>
              <th>Players</th>
            </tr>
          </thead>

          <tbody>
            <% @games.each do |game| %>
            <tr>
              <td><%= game.sport.name %></td>
              <td><%= link_to game.street_address, game_path(game) %></td>
              <td><%= game.start_date %></td>
              <td><%= game.start_date.strftime("%l:%M%p") %></td>
                <% if game.description.empty? %>
                  <td>N/A</td>
                <% else %>
                  <td><%= game.description %></td>
                <% end %>
              </td>
                <% if game.players.count == game.max_players %>
              <td>FULL</td>
                <% else %>
              <td><%= game.players.count %>/<%= game.max_players %></td>
                <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>

    </div>
  </div>


</div>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<table id="table_id" class="display">
  <thead>
    <tr>
      <th>User</th>
      <th>Email</th>
      <th>Sign in Count</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
    <% if user.image.nil? %>
      <td><%= image_tag("default.png") %><%= user.name %></td>
    <% else %>
      <td><%= image_tag(user.image) %><%= user.name %></td>
    <% end %>
      <td><%= user.email %></td>
      <td><%= user.sign_in_count %></td>
      <td><%= button_to "Delete this user", admin_user_path(user), method: :delete %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/games/index.html.erb
<div id="featured">

<div class="row">
  <div class="small-10 columns small-centered">
    <div class="create-row large-8 small-12 small-centered columns">

      <% if params[:q].present? %>
        <h2 id="index-header">Games matching</h2><p>"<%= params[:q] %>"</p>
      <% else %>
        <h2 id="index-header">Games</h2>
      <% end %>

      <%= link_to new_game_path, class:"create tiny button expand", id:"new game" do %>
        <i class="fa fa-plus"></i> New Game
      <% end %>
    </div>

    <table id="table_id" class="display">
      <thead>
        <tr>
          <th>Sport</th>
          <th>Address</th>
          <th>Date</th>
          <th>Time</th>
          <th>Additional info</th>
          <th>Players</th>
        </tr>
      </thead>

      <tbody>
        <% @games.each do |game| %>
        <tr>
          <td><%= game.sport.name %></td>
          <td><%= link_to game.street_address, game_path(game) %></td>
          <td><%= game.start_date %></td>
          <td><%= game.start_date.strftime("%l:%M%p") %></td>
            <% if game.description.empty? %>
              <td>N/A</td>
            <% else %>
              <td><%= game.description %></td>
            <% end %>
          </td>
            <% if game.players.count == game.max_players %>
          <td>FULL</td>
            <% else %>
          <td><%= game.players.count %>/<%= game.max_players %></td>
            <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

</div>

app/views/games/new.html.erb
<div id="featured">

  <div class="row">
    <div class="small-10 columns small-centered">

      <h1 class="form-title">Create a Game</h1>

      <h5>Don't see your sport? Add it to our database <%= link_to "here", new_sport_path %>.</h5>

      <%= form_for @game do |f| %>

        <%= f.label :sport %>
        <%= f.collection_select :sport_id, Sport.all.order('name'), :id, :name %>

        <%= f.label "Start date and time" %>
        <%= f.text_field :start_date, value: "#{Date.today}", min: Date.today %>

        <div id="locationField">
          <label for="street_address">Enter Address</label>
          <input id="autocomplete" placeholder="Enter address"
             onFocus="geolocate()" type="text" name="game[street_address]"></input>
        </div>

        <%= f.label "Additional Information/Directions (optional)" %>
        <%= f.text_field :description, placeholder: "e.g., Field #3" %>

        <%= f.label :max_players %>
        <%= f.number_field :max_players %>

        <%= f.submit "Create Game", class:"create tiny button expand" %>

      <% end %>

    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="contains-map small-12 small-centered columns">

  <ul class="pricing-table small-12 small-centered columns">
    <li class="title">
      <div class="large-10 medium-11 small-12 small-centered columns">
        <div class"google-maps">
          <iframe
           width="640"
           height="450"
           frameborder="0" style="border:0"
           src="https://www.google.com/maps/embed/v1/place?key=<%= ENV["GOOGLE_KEY"] %>
             &q=<%= @address %>
             &attribution_source=Google+Maps+Embed+API
             &attribution_ios_deep_link_id=comgooglemaps://?daddr=<%= @address %>">
          </iframe>
        </div>
      </div>
    </li>

    <li class="bullet-item">
      <div class="small-8 small-centered columns">
        <h1><%= @game.sport.name %></h1><br>
          <%= link_to games_path do %>
            <i class="fa fa-globe"></i> Back to all games
          <% end %>
      </div>
    </li>

    <li class="bullet-item">
    <h6>Address:</h6><%= @address %><br><br><br>
    <h6>Date and time:</h6><%= @game.start_date.strftime("%A, %B %d") %><br><%= @game.start_date.strftime("%l:%M %p")%><br><br><br>
    <h6>Additional information:</h6>
      <%= @game.description? %>

      <% if @player.nil? %>
        <%= button_to "Join Game", game_players_path(@game), method: :post, class: "join tiny button expand" %>
      <% else %>
        <%= button_to "Leave Game", game_player_path(@game, @player), method: :delete, class: "leave tiny button expand" %>
      <% end %>
    </li>

    <li class="bullet-item">
      <table class="player-table small-12 medium-6 large-4 small-centered columns">
        <thead>
          <tr>
            <th>
              <i class="fa fa-users"></i>  Players
              <div class:"status">Status: ( <%= @game.full? %>  )
            </th>
          </tr>
        </thead>
        <% @players.each do |player| %>
        <tbody>
          <tr>
            <% if player.user.image.nil? %>
              <td><%= image_tag("default.png") %><%= player.user.name %></td>
            <% else %>
              <td><%= image_tag(player.user.image) %><%= player.user.name %></td>
            <% end %>
          </tr>
        </tbody>
        <% end %>
      </table>
    </li>

    <% if @game.user == current_user %>
      <li class="bullet-item">
        <%= button_to "Delete Game", game_path, method: :delete, class: "delete tiny button expand", data: { confirm: "Are you sure you want to delete this game? It will no longer be visible to other players." } %>
      </li>
    <% end %>
  </ul>

</div>

<footer class="panel">
  <div class="row">
    <hr>
    <div class="small-7 medium-8 columns">© 2015 - Created by <%= link_to "Brian Stern", "https://github.com/bsterno" %></div>
    <div class="small-4 columns">
      <ul class="inline-list right">
        <li><a href="https://www.linkedin.com/in/sternbrian"><i class="fa fa-linkedin"></i></a></li>
        <li><a href="https://github.com/bsterno"><i class="fa fa-github"></i></a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/homes/index.html.erb
<div id="featured">
  <div class="row">

    <div class="small-12 small-centered columns main-logo-box">
      <%= link_to image_tag('arrow_logo_360.png', class:"main-logo"), games_path %>
      <div class="eam">
        <h1>eamUP</h1>
      </div>
    </div>
    <hr class="sexy-line">
    <p class="small-12 small-centered columns tag-line">CASUAL SPORTS MADE EASY</p>
      <div class="small-12 small-centered columns search-box">
        <div id="search">
            <%= form_tag games_path, method: :get do %>
              <%= text_field_tag :q, params[:q], placeholder: "Search by Location", class:"aaa-search-input" %>
              <button class="aaa-search-btn" type="submit" id="bitton"><i class="fa fa-search"></i>
            <% end %>
        </div>
      </div>

  </div>
</div>

<div class="row hide-for-small-only">
  <div class="featured-content medium-9 small-12 small-centered columns">
    <h3><div class="shake shake-slow"><a href="/games"><i class="fa fa-futbol-o"></i></div></a> GAME ON!</h3>
    <p>Discover, join, and play games with people in your area.
    TeamUP makes it easy for anyone to organize or join casual sports.</p>
  </div>
</div>

<div class="row show-for-small-only">
  <div class="featured-content medium-9 small-12 small-centered columns">
    <h1><div class="shake shake-slow"><a href="/games"><i class="fa fa-futbol-o"></i></div></a> GAME ON!</h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= favicon_link_tag 'arrow_logo_360.ico' %>
<html>
<head>
  <title>TeamUP</title>
  <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places"></script>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Raleway', media: 'all' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body onload="initialize()">

<% if current_page?(new_game_path) %>
  <div class="page-wrap small-12 small-centered columns" style="height: 125%;">
<% elsif current_page?(edit_user_registration_path) %>
  <div class="page-wrap small-12 small-centered columns" style="height: 160%;">
<% else %>
  <div class="page-wrap small-12 small-centered columns">
<% end %>

    <div class="main-image">
      <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
              <%= link_to image_tag('arrow_logo_360.png'), root_path, class:"logo" %><h1 class="logo-end">eamUP</h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <ul class="right">
              <%- if current_user -%>
                <li class="divider"></li>
                <li class="sign-in"><%= link_to 'All Games', games_path %></li>
                <li class="divider"></li>
                <li class="sign-in"><%= link_to 'My Games', user_path(current_user) %></li>
                <li class="divider"></li>
                <li class="sign-in"><%= link_to 'New Game', new_game_path %></li>
                <li class="divider"></li>
                <li class="sign-in"><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                <li class="divider"></li>
                <li class="sign-in"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
              <%- else -%>
                <li class="divider"></li>
                <li class="sign-in"><%= link_to 'All Games', games_path %></li>
                <li class="divider"></li>
                <li class="sign-in"><%= link_to 'New Game', new_game_path %></li>
                <li class="divider"></li>
                <li class="sign-in"><%= link_to 'Sign Up', new_user_registration_path %></li>
                <li class="divider"></li>
                <li class="sign-in"><%= link_to 'Sign In', new_user_session_path %></li>
              <%- end -%>
          </ul>
        </section>
      </nav>

        <div class="small-6 small-centered columns">
          <% flash.each do |key, value| %>
              <div data-alert class="flash <%= key %> alert-box radius">
                <% value.split("\n").each do |f| %>
                  <%= f %><br>
                <a href="#" class="close">&times;</a>
                <% end %>
              </div>
          <% end %>
        </div>

        <div id="content">
          <%= yield %>
        </div>
    </div>
  </div>

        <%= javascript_include_tag 'application' %>

  <% unless current_page?(root_path) || (params[:controller] == "games" && params[:action] == "show") %>
    <footer class="panel">
      <div class="row">
        <hr>
        <div class="small-8 columns">© 2015 - Created by <%= link_to "Brian Stern", "https://github.com/bsterno" %></div>
        <div class="small-4 columns">
          <ul class="inline-list right">
            <li><a href="https://www.linkedin.com/in/sternbrian"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="https://github.com/bsterno"><i class="fa fa-github"></i></a></li>
          </ul>
        </div>
      </div>
    </footer>
  <% end %>

</body>
</html>

app/views/sports/new.html.erb
<div id="featured">
  <div class="row">
    <div class="small-10 columns small-centered">

      <h1 class="form-title">Add Sport</h1>

      <%= form_for @sport do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.submit "Add Sport", class: "join tiny button expand" %>
      <% end %>
      <br>
      <%= link_to "Create game", new_game_path, class: "create tiny button expand", id: "sport-form" %>
      <br>
      <p><%= link_to "Back to all games", games_path %></p>

    </div>
  </div>
</div>

app/views/stats/index.html.erb
<div id="featured">

  <div class="row">
    <div class="small-10 columns small-centered">
      <div class="create-row large-8 small-12 small-centered columns">

          <h2 id="index-header">Data and Statistics</h2>
          <h1><%= Stat.sports %></h1>

      </div>

      <%= pie_chart Stat.sports %>

        <table id="table_id" class="display">
          <thead>
            <tr>
              <th>Sport</th>
              <th>Address</th>
              <th>Date</th>
              <th>Time</th>
              <th>Additional info</th>
              <th>Players</th>
            </tr>
          </thead>

          <tbody>
            <% @games.each do |game| %>
            <tr>
              <td><%= game.sport.name %></td>
              <td><%= link_to game.street_address, game_path(game) %></td>
              <td><%= game.start_date %></td>
              <td><%= game.start_date.strftime("%l:%M%p") %></td>
                <% if game.description.empty? %>
                  <td>N/A</td>
                <% else %>
                  <td><%= game.description %></td>
                <% end %>
              </td>
                <% if game.players.count == game.max_players %>
              <td>FULL</td>
                <% else %>
              <td><%= game.players.count %>/<%= game.max_players %></td>
                <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>

    </div>
  </div>


</div>

app/views/users/show.html.erb
<div id="featured">

<div class="row">
  <div class="small-10 columns small-centered">
    <div class="create-row medium-9 small-12 small-centered columns">
      <h1 id="index-header">
        <% if current_user.image == nil %>
          <%= image_tag("default.png") %>
        <% else %>
          <%= image_tag(current_user.image) %>
        <% end %>
        My Games</h1>
      <%= link_to new_game_path, class:"create tiny button expand" do %>
        <i class="fa fa-plus"></i> New Game
      <% end %>
    </div>

    <table id="table_id" class="display">
      <thead>
        <tr>
          <th>Sport</th>
          <th>Address</th>
          <th>Date</th>
          <th>Time</th>
          <th>Additional info</th>
          <th>Players</th>
        </tr>
      </thead>

      <tbody>
        <% @games.each do |game| %>
        <tr>
          <td><%= game.game.sport.name %></td>
          <td><%= link_to game.game.street_address, game_path(game.game) %></td>
          <td><%= game.game.start_date %></td>
          <td><%= game.game.start_date.strftime("%l:%M%p") %></td>
            <% if game.game.description.empty? %>
              <td>N/A</td>
            <% else %>
              <td><%= game.game.description %></td>
            <% end %>
          </td>
            <% if game.game.players.count == game.game.max_players %>
          <td>FULL</td>
            <% else %>
          <td><%= game.game.players.count %>/<%= game.game.max_players %></td>
            <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

</div>